import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ProductGrid from './components/productgrid'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>J.Crew Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          J. Crew
        </h1>

        <p className={styles.description}>
          Products
        </p>

        <div className={styles.grid}>
          <ProductGrid />
        </div>
      </main>

    </div>
  )
}
